### ISSUE TITLE
画面デザインの適用

### ISSUE THREAD

**Issue by ai161** [itsp-pbl-2023/mind-graph#76]
https://www.figma.com/file/dkCKsMdmZdbsEu7W349Zyw/Mind-Graph?type=design&node-id=0%3A1&t=UfVZueY0H5F1Ojvk-1

**Comment by NapoliN** [comment]
- フォント
- ボタンデザイン
- フォームデザイン
- 名前表示デザイン

**Comment by ai161** [comment]
フォント：sakashita
ボタン：sakashita
フォーム：ha
名前表示：nagatomo
timer：sakashita

**Comment by NapoliN** [comment]
タイトルも私がやった

**Comment by ai161** [comment]
名前表示
font
ボタン
フォーム
タイトル
done
